### ISSUE TITLE
Freedrive button installation

### ISSUE THREAD

**Issue by afonsocastro** [afonsocastro/larcc_interface#3]
In order to ease the creation process of future features, it would be very helpful to have an external button with the _freedrive_ function.
With the purpose of creating a hand-free system, the external button should be a pedal, being the pedal the most suitable solution.

Our UR10e cobot already has the _FreeDrive_ mode installed and working on the Teach Pendant, by continuously pressing the small round black button that is on the Teach Pendant back. 
The gold here is to take that feature to the external pedal, probably by using the controller I/Os.

The UR10e user manual can be found here: [https://s3-eu-west-1.amazonaws.com/ur-support-site/41240/UR10e_User_Manual_en_US.pdf](https://s3-eu-west-1.amazonaws.com/ur-support-site/41240/UR10e_User_Manual_en_US.pdf)

I think the proper pages to the better I/Os understanding are in the 5.4 chapter "_Controller I/O_". (page I-30 to page I-40)

**Comment by Joel-Baptista** [comment]
The task is completed. The system is working with a pedal that closes the connection between the 24V source and the DI0, which activates the FreeDrive mode. Now, the activation of the FreeDrive mode is hands-free and doesn't require the dashboard
