### ISSUE TITLE
Utils Library for arm and gripper control 

### ISSUE THREAD

**Issue by afonsocastro** [afonsocastro/larcc_interface#4]
By this time, each different experiment can communicate with the _arm controller_ and the _gripper controller_ for its own interest.
This communication is at the same level for both controllers.
Here is a representation of the first experiment, which I called "_job1_":
![image](https://user-images.githubusercontent.com/47828797/161547848-d92ab696-8cf8-4184-85a0-8b578f08314e.png)
As you can see, "_job1_" is communicating with _arm controller and _gripper controller_.

To ease the future experiments (jobs) creation, it is required to create a fully working python3 library, that would take care of all this communication procedure. 

We can see this "_job1_" code here: [demo1.py](https://github.com/afonsocastro/larcc_interface/blob/master/use_cases/src/demo1/demo1.py).

I think the best way is to create a new demo (demo2 for example), just to try the new library. Mostly because this demo1 requires the IntelRealsense RGB-D camera connection and that is not needed for this issue. Probably something like [test_sequence.py](https://github.com/afonsocastro/larcc_interface/blob/master/use_cases/src/demo1/test_sequence.py) is a more appropriate approach.

There is a first trial for this library on the [utils paste](https://github.com/afonsocastro/larcc_interface/tree/master/use_cases/src/utils), but its not working right now. I am not sure if its best to delete this utils paste and start from scratch or if there is something here that can be useful.

**Comment by Joel-Baptista** [comment]
@afonsocastro I'm having trouble connecting with UR10e. I created a launch file demo2.launch, which a copy of test_sequence.launch:

```
<?xml version="1.0"?>

<launch>
    <include file="$(find ur_robot_driver)/launch/ur10e_bringup.launch">
        <arg name="robot_ip" value="192.168.56.1"/>
    </include>

<!--    <include file="$(find ur10e_moveit_config)/launch/ur10e_moveit_planning_execution.launch">-->
<!--    </include>-->

<!--    <node pkg="use_cases" type="demo2.py" name="demo2"/>-->


<!--    <node pkg="gripper" type="gripper_controller.py" name="gripper_controller"/>-->
<!--    <node pkg="arm" type="arm_controller.py" name="arm_controller"/>-->
</launch>
```
I'm just trying to launch the scripts that open the connection between the computer and the robot. In the robot's dashboard it showed the IP was 192.168.56.1.

When I run the launch file, this error appears:

```
[ INFO] [1649689642.930133514]: Initializing dashboard client
[ INFO] [1649689642.936025119]: Waiting for controller manager service to come up on /controller_manager/switch_controller
[ INFO] [1649689642.936996034]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
[ INFO] [1649689642.944600215]: waitForService: Service [/ur_hardware_interface/dashboard/play] has not been advertised, waiting...
[INFO] [1649689643.210475]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1649689643.296815]: Remote device is available at '/tmp/ttyUR'
[INFO] [1649689643.298627]: Starting socat with following command:
socat pty,link=/tmp/ttyUR,raw,ignoreeof,waitslave tcp:192.168.56.1:54321
[INFO] [1649689643.307891]: Controller Spawner: Waiting for service controller_manager/load_controller
[ERROR] [1649689645.989078165]: Connection setup failed for 192.168.56.1:29999
[ INFO] [1649689646.004331894]: Initializing urdriver
[ INFO] [1649689646.015297587]: waitForService: Service [/ur_hardware_interface/dashboard/play] is now available.
[ERROR] [1649689649.057088859]: Connection setup failed for 192.168.56.1:30002
[ERROR] [1649689652.129069128]: Connection setup failed for 192.168.56.1:30004
[FATAL] [1649689657.129532251]: Failed to connect to robot. Please check if the robot is booted and connected.
[ERROR] [1649689657.129662372]: Could not correctly initialize robot. Exiting
================================================================================REQUIRED process [ur_hardware_interface-3] has died!
process has died [pid 66488, exit code 1, cmd /home/joel/catkin_ws/devel/lib/ur_robot_driver/ur_robot_driver_node __name:=ur_hardware_interface __log:=/home/joel/.ros/log/169c1e06-b9a9-11ec-9f6a-4deddf7c5502/ur_hardware_interface-3.log].
log file: /home/joel/.ros/log/169c1e06-b9a9-11ec-9f6a-4deddf7c5502/ur_hardware_interface-3*.log
Initiating shutdown!
================================================================================

```

The ethernet connection seems fine. When I run ifconfig it shows the following (I think enx9cebe806b734 is the ethernet connection):

```
enx9cebe806b734: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 9c:eb:e8:06:b7:34  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 983  bytes 182900 (182.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Loopback Local)
        RX packets 198277  bytes 69693296 (69.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 198277  bytes 69693296 (69.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlo1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.59.81  netmask 255.255.224.0  broadcast 192.168.63.255
        inet6 fe80::37e1:7b9e:d48f:645c  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::5635:eccc:fc5:282b  prefixlen 64  scopeid 0x20<link>
        ether 00:e9:3a:d4:26:fd  txqueuelen 1000  (Ethernet)
        RX packets 718542  bytes 897200212 (897.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 119958  bytes 24328762 (24.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
I searched all day about this topic and will continue to try to solve it, but if you know anything let me know

**Comment by Joel-Baptista** [comment]
@afonsocastro also, I don't now if it's related, but in the ur_control.launch, the package ur_client_library
```
<arg name="urscript_file" default="$(find ur_client_library)/resources/external_control.urscript" doc="Path to URScript that will be sent to the robot and that forms the main control program."/>
```
I couldn't find myself the package in the repository. Maybe that's a package that you have outside the repository in your local machine?

**Comment by afonsocastro** [comment]
@Joel-Baptista check your email please. Call me

**Comment by Joel-Baptista** [comment]
@afonsocastro The issue was fixed by following the steps in the repository's REAM.ME. It was very helpfull and simple to follow. I I already controlled UR10 with Rviz and I'm starting to try demo2.py. It has some errors, but I'm trying to fix it

**Comment by afonsocastro** [comment]
Those are very good news!
Good job so far

**Comment by Joel-Baptista** [comment]
I believe the task is completed. A first version of the library was created with all the functions in test_sequence.py. This library was tested in the script demo2.py and it seems functional
